# Generated by Django 4.1.2 on 2022-10-05 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Аллергия',
                'verbose_name_plural': 'Аллергии',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип меню',
                'verbose_name_plural': 'Типы меню',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=6, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Приемы пищи',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('content', models.TextField(verbose_name='Состав')),
                ('calories', models.IntegerField(verbose_name='Калорийность')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('allergies', models.ManyToManyField(related_name='recipes', to='backend.allergy', verbose_name='Аллергии')),
                ('menus', models.ManyToManyField(related_name='recipes', to='backend.menu', verbose_name='Типы меню')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persons', models.IntegerField(default=1, verbose_name='Количество персон')),
                ('calories', models.IntegerField(verbose_name='Калории')),
                ('price', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Цена')),
                ('start_time', models.DateField(auto_now_add=True, verbose_name='Дата начала')),
                ('lenght', models.IntegerField(verbose_name='Продолжительность подписки')),
                ('allergies', models.ManyToManyField(related_name='orders', to='backend.allergy', verbose_name='Аллергии')),
                ('menus', models.ManyToManyField(related_name='orders', to='backend.menu', verbose_name='Меню')),
                ('types', models.ManyToManyField(related_name='orders', to='backend.type', verbose_name='Приемы пищи')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
    ]
