# Generated by Django 4.1.2 on 2022-10-05 14:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Прием пищи', 'verbose_name_plural': 'Приемы пищи'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='lenght',
        ),
        migrations.AddField(
            model_name='order',
            name='finish_time',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата окончания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='allergy',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='type',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
