# Generated by Django 4.1.2 on 2022-10-05 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='allergies',
            field=models.ManyToManyField(blank=True, related_name='orders', to='backend.allergy', verbose_name='Аллергии'),
        ),
        migrations.AlterField(
            model_name='order',
            name='menus',
            field=models.ManyToManyField(blank=True, related_name='orders', to='backend.menu', verbose_name='Меню'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='allergies',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='backend.allergy', verbose_name='Аллергии'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='menus',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='backend.menu', verbose_name='Типы меню'),
        ),
        migrations.CreateModel(
            name='RecipeShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата показа')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='backend.recipe', verbose_name='Рецепт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Показ',
                'verbose_name_plural': 'Показы',
            },
        ),
    ]
