# Generated by Django 4.1.2 on 2022-10-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_order_allergies_alter_order_menus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.JSONField(default={}, verbose_name='Ингредиенты'),
        ),
    ]
