# Generated by Django 4.1.2 on 2022-10-09 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Действует'),
        ),
        migrations.CreateModel(
            name='YookassaPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(db_index=True, max_length=40, verbose_name='Идентификатор')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='backend.order', verbose_name='Подписка')),
            ],
        ),
    ]
