# Generated by Django 4.1.2 on 2022-10-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_order_is_active_yookassapayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='yookassapayment',
            name='is_pending',
            field=models.BooleanField(default=True, verbose_name='Ожидает оплаты'),
        ),
    ]
